Финальное задание спринта 9
EvgeniyaLukyanova/java-filmorate pull request #2
Opened 2023-03-07 20:28 UTC by EvgeniyaLukyanova

2023-03-07 20:35 UTC, EvgeniyaLukyanova commented
Финальное задание спринта 9

2023-03-08 19:07 UTC, TarasovSam requested changes
Привет! В целом - все довольно хорошо) Отметил то, что следует исправить и то, что можно сделать лучше, плюс постарался ответить на твои вопросы.
Жду твою работу на следующую итерацию!) Если будут вопросы, пиши в пачку.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidateService.java
> +    final FilmRepository repository;
Для соблюдения инкапсуляции - поля класса должны быть приватными.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidateService.java
> +        if (film.getDescription().length() > 200) {
Для начала следует проверить значение на null, иначе есть шанс возникновения NPE.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidateService.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Для начала следует проверить значение на null, иначе есть шанс возникновения NPE.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmValidateService.java
> +        if (film.getDuration() < 0) {
Для начала следует проверить значение на null, иначе есть шанс возникновения NPE.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserValidateService.java
> +    final UserRepository repository;
Для соблюдения инкапсуляции - поля класса должны быть приватными.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserValidateService.java
> +        if (user.getLogin().contains(" ")) {
Эта проверка по сути не нужна, т.к. предыдущая содержит isBlank, который проверяет как раз на пробелы.

2023-03-08 19:07 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/service/UserValidateService.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
Для начала следует проверить значение на null, иначе есть шанс возникновения NPE.

2023-03-10 14:39 UTC, TarasovSam reviewed
Евгения, спасибо за то, что вносишь корректировки по рекомендациям. Оставил еще пару комментариев для проработки.
Задание я принимаю, успеха в обучении и до следующего спринта!) Если будут вопросы, пиши в пачку.

2023-03-10 14:39 UTC, TarasovSam commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
По ТЗ дата релиза — не раньше 28 декабря 1895 года, т.е. дата релиза может отсутствовать)
Поэтому аннотация здесь не нужна, а вот проверку на null следует прописать в валидации перед проверкой, что она не раньше 28 декабря 1895 года.

2023-03-18 14:42 UTC, merged